version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:8080"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    restart: unless-stopped
