# Usa Python slim image
FROM python:3.12-slim

# Imposta variabili d'ambiente
ENV DEBIAN_FRONTEND=noninteractive
ENV WHISPER_MODEL=medium

# Installa dipendenze di sistema
RUN apt-get update 
RUN apt-get install -y openssh-server
# RUN apt-get install -y ffmpeg
# RUN apt-get install -y wget
# RUN apt-get install -y curl
#RUN apt-get install -y git
RUN rm -rf /var/lib/apt/lists/*

# Configura SSH
RUN mkdir -p /var/run/sshd
RUN echo 'root:1234' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config





# Crea directory app
WORKDIR /app

# Copia codice applicazione
COPY . .


# Installa dipendenze Python aggiuntive
RUN pip install -r requirements.txt

# Espone le porte
EXPOSE 12347
EXPOSE 12348

# Script di avvio
# RUN echo '#!/bin/bash\n\
# # Avvia SSH in background\n\
# /usr/sbin/sshd -D -e &\n\
# # Avvia applicazione\n\
# python3 /app/src/main.py' > /start.sh && chmod +x /start.sh

RUN echo '#!/bin/bash\n\
# Avvia SSH in background\n\
/usr/sbin/sshd -D -e' > /start.sh && chmod +x /start.sh

# Imposto lo script come entrypoint
ENTRYPOINT ["/start.sh"]

# Comando di avvio
#CMD ["/start.sh"]